spring.application.name=exam-portal

# ── Database ──────────────────────────────────────────────────────────────────
spring.datasource.url=jdbc:mysql://localhost:3306/exam_portal?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC

spring.datasource.username=root1
spring.datasource.password=00000
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ── JPA ───────────────────────────────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ── JWT ───────────────────────────────────────────────────────────────────────
# 256-bit base64-encoded secret key
app.jwt.secret=dGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXkgZm9yIGV4YW0gcG9ydGFsIGp3dA==
app.jwt.access-token-expiry-ms=000
app.jwt.refresh-token-expiry-ms=0000

# ── Anti-Cheat ────────────────────────────────────────────────────────────────
app.exam.max-violations=3

# ── CORS ──────────────────────────────────────────────────────────────────────
app.cors.allowed-origins=http://localhost:3000

# ── Swagger ───────────────────────────────────────────────────────────────────
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
server.port=9090
